"""Recreate missing migration

Revision ID: 12c82fa2cf48
Revises: 
Create Date: 2025-03-10 16:41:55.696790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c82fa2cf48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_disease_name', sa.String(length=255), nullable=False),
    sa.Column('category_disease_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_disease')
    # ### end Alembic commands ###
