"""create applicationform

Revision ID: 375ef7f06c62
Revises: 639a76deb55a
Create Date: 2025-03-18 09:29:02.882216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ef7f06c62'
down_revision = '639a76deb55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('application_form_date', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medical_history_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_forms')
    # ### end Alembic commands ###
