"""fix diagnose disease model

Revision ID: 6210110f031d
Revises: 12c82fa2cf48
Create Date: 2025-03-10 17:44:32.461444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6210110f031d'
down_revision = '12c82fa2cf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnose_disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnose_disease_name', sa.String(length=255), nullable=False),
    sa.Column('diagnose_disease_description', sa.Text(), nullable=False),
    sa.Column('category_disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_disease_id'], ['category_disease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnose_disease')
    # ### end Alembic commands ###
