"""create model medical history

Revision ID: 639a76deb55a
Revises: 09ded9ec5dac
Create Date: 2025-03-17 16:58:22.157893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639a76deb55a'
down_revision = '09ded9ec5dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_histories')
    # ### end Alembic commands ###
