"""Add quantity_patient column to specicalization

Revision ID: 72ee37f212dc
Revises: 2d0969d864dc
Create Date: 2025-03-03 06:22:40.988305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ee37f212dc'
down_revision = '2d0969d864dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_patient', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_column('quantity_patient')

    # ### end Alembic commands ###
