"""Recreate migrations

Revision ID: 7cc7422212d3
Revises: df405f92d6d3
Create Date: 2025-03-10 15:14:10.580185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc7422212d3'
down_revision = 'df405f92d6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_disease_name', sa.String(length=255), nullable=False),
    sa.Column('type_disease_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_disease')
    # ### end Alembic commands ###
