"""chage type Date to application_form_date

Revision ID: 80b9a92fb1a3
Revises: e2622e7b1715
Create Date: 2025-03-21 15:08:43.788269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80b9a92fb1a3'
down_revision = 'e2622e7b1715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_forms', schema=None) as batch_op:
        batch_op.alter_column('application_form_date',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_forms', schema=None) as batch_op:
        batch_op.alter_column('application_form_date',
               existing_type=sa.Date(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    # ### end Alembic commands ###
