"""create model disease category

Revision ID: 8fb969c5ad91
Revises: 
Create Date: 2025-03-09 20:37:06.490334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb969c5ad91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_category_disease', sa.String(length=100), nullable=False),
    sa.Column('description_category_disease', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description_category_disease'),
    sa.UniqueConstraint('name_category_disease')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_category')
    # ### end Alembic commands ###
