"""create model images

Revision ID: af93e1a56eef
Revises: b5fc4823c349
Create Date: 2025-03-30 15:04:54.127756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af93e1a56eef'
down_revision = 'b5fc4823c349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('images_path', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disease_id'], ['diagnose_disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
