"""update model appointment form 

Revision ID: b189847f8051
Revises: fc0a41ef242f
Create Date: 2025-03-30 15:29:10.336707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b189847f8051'
down_revision = 'fc0a41ef242f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_form_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diagnose_disease_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('images_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('images_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'diagnose_disease', ['diagnose_disease_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'appointment_forms', ['appointment_form_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('disease_id')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('disease_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('images_ibfk_1', 'appointment_forms', ['appointment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('images_ibfk_2', 'diagnose_disease', ['disease_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('diagnose_disease_id')
        batch_op.drop_column('appointment_form_id')

    # ### end Alembic commands ###
