"""create model appointment

Revision ID: b5fc4823c349
Revises: 92d653311ac1
Create Date: 2025-03-23 08:59:06.919029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fc4823c349'
down_revision = '92d653311ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('application_form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_forms')
    # ### end Alembic commands ###
