"""update foreignkey

Revision ID: bc926150ac5b
Revises: 375ef7f06c62
Create Date: 2025-03-18 12:46:35.998704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc926150ac5b'
down_revision = '375ef7f06c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
