"""delete patient_id for medical history

Revision ID: bcd24b8a86e4
Revises: 80b9a92fb1a3
Create Date: 2025-03-21 16:10:54.522166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd24b8a86e4'
down_revision = '80b9a92fb1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_histories', schema=None) as batch_op:
        batch_op.drop_constraint('medical_histories_ibfk_2', type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('medical_histories_ibfk_2', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
