"""add date

Revision ID: ce3fadf5e9be
Revises: bcd24b8a86e4
Create Date: 2025-03-21 16:43:32.892057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3fadf5e9be'
down_revision = 'bcd24b8a86e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_histories', schema=None) as batch_op:
        batch_op.drop_column('calendar_date')

    # ### end Alembic commands ###
