from .account import Account
from .specialization import Specialization
from .education import Education
from .category_disease import Category_Disease
from .diagnose_disease import Diagnose_Disease
from .physician import Physician
from .patient import Patient
from .room import Room
from .medical_history import MedicalHistory
from .application_form import ApplicationForm
from .appointment_form import AppointmentForm